---
  - name: Download the JDK binaries
    ansible.builtin.get_url:
      url: "{{ jdk_download_url }}"
      dest: "{{ jdk_download_location }}"
  - name: Unzip the downloaded file
    ansible.builtin.unarchive:
      src: "{{ jdk_download_location }}"
      dest: /opt
      remote_src: yes

  - name: Set the JAVA_HOME in /etc/profile file
    ansible.builtin.lineinfile:
      path: /etc/profile
      state: present
      line: "{{ item }}"
    with_items:
      - 'export JAVA_HOME="{{ java_home }}"'
      - 'export PATH=$PATH:$JAVA_HOME/bin'

  - name: Reload /etc/profile file
    ansible.builtin.shell:
      cmd: . /etc/profile

